# Generated by Django 5.2.7 on 2025-10-29 04:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('laboratory_enrollment_start', models.DateField()),
                ('laboratory_enrollment_end', models.DateField()),
                ('enrollment_change_deadline', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
                'db_table': 'academic_periods',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.IntegerField()),
                ('theory_hours', models.IntegerField(default=0)),
                ('practice_hours', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institutional_email', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('role', models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Profesor'), ('secretary', 'Secretario'), ('admin', 'Administrador')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_code', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('enrolled_students', models.IntegerField(default=0)),
                ('schedule_info', models.JSONField(blank=True, null=True)),
                ('classroom', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgres_repository.academicperiod')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgres_repository.course')),
            ],
            options={
                'verbose_name': 'Grupo de Curso',
                'verbose_name_plural': 'Grupos de Curso',
                'db_table': 'course_groups',
            },
        ),
        migrations.CreateModel(
            name='EstudianteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Estudiante')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('correo_institucional', models.EmailField(max_length=254, unique=True, verbose_name='Correo Institucional')),
                ('estado', models.CharField(choices=[('DESACTIVADO', 'Desactivado'), ('ACTIVO', 'Activo'), ('RETIRADO', 'Retirado'), ('ABANDONO', 'Abandono')], default='DESACTIVADO', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_legacy', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado')),
            ],
            options={
                'verbose_name': 'Estudiante (Legacy)',
                'verbose_name_plural': 'Estudiantes (Legacy)',
                'db_table': 'estudiantes_legacy',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='LaboratorioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Laboratorio')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('COMPUTO', 'Laboratorio de Cómputo'), ('FISICA', 'Laboratorio de Física'), ('QUIMICA', 'Laboratorio de Química'), ('ELECTRONICA', 'Laboratorio de Electrónica'), ('AULA', 'Aula Regular'), ('AUDITORIO', 'Auditorio')], default='COMPUTO', max_length=20, verbose_name='Tipo de Laboratorio')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad Máxima')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('equipamiento', models.TextField(blank=True, verbose_name='Descripción del Equipamiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Laboratorio Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'db_table': 'laboratorios',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo'], name='idx_laboratorio_codigo'), models.Index(fields=['tipo'], name='idx_laboratorio_tipo'), models.Index(fields=['activo'], name='idx_laboratorio_activo')],
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lab_code', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('enrolled_students', models.IntegerField(default=0)),
                ('schedule_info', models.JSONField()),
                ('lab_room', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgres_repository.coursegroup')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'db_table': 'laboratories',
            },
        ),
        migrations.CreateModel(
            name='MatriculaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo_academico', models.CharField(max_length=20, verbose_name='Período Académico')),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RETIRADA', 'Retirada'), ('ANULADA', 'Anulada')], default='ACTIVA', max_length=20, verbose_name='Estado')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='postgres_repository.estudiantemodel')),
            ],
            options={
                'verbose_name': 'Matrícula (Legacy)',
                'verbose_name_plural': 'Matrículas (Legacy)',
                'db_table': 'matriculas_legacy',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_code', models.CharField(max_length=20, unique=True)),
                ('career', models.CharField(blank=True, max_length=100, null=True)),
                ('current_cycle', models.IntegerField(blank=True, null=True)),
                ('academic_status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='LaboratoryEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('withdrawn', 'Retirado')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgres_repository.laboratory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgres_repository.student')),
            ],
            options={
                'verbose_name': 'Matrícula de Laboratorio',
                'verbose_name_plural': 'Matrículas de Laboratorio',
                'db_table': 'laboratory_enrollments',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('enrollment_type', models.CharField(choices=[('regular', 'Regular'), ('special', 'Especial')], default='regular', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('withdrawn', 'Retirado'), ('failed', 'Desaprobado')], default='active', max_length=20)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgres_repository.academicperiod')),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgres_repository.coursegroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgres_repository.student')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teacher_code', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('hours_per_week', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'teachers',
            },
        ),
        migrations.AddField(
            model_name='laboratory',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postgres_repository.teacher'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postgres_repository.teacher'),
        ),
        migrations.AddIndex(
            model_name='estudiantemodel',
            index=models.Index(fields=['codigo'], name='idx_estudiante_codigo'),
        ),
        migrations.AddIndex(
            model_name='estudiantemodel',
            index=models.Index(fields=['correo_institucional'], name='idx_estudiante_correo'),
        ),
        migrations.AddIndex(
            model_name='estudiantemodel',
            index=models.Index(fields=['estado'], name='idx_estudiante_estado'),
        ),
        migrations.AlterUniqueTogether(
            name='matriculamodel',
            unique_together={('estudiante', 'periodo_academico')},
        ),
        migrations.AlterUniqueTogether(
            name='laboratoryenrollment',
            unique_together={('student', 'laboratory')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course_group', 'academic_period')},
        ),
        migrations.AlterUniqueTogether(
            name='coursegroup',
            unique_together={('course', 'academic_period', 'group_code')},
        ),
    ]
