# Generated by Django 5.2.7 on 2025-10-15 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Código CUI')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('correo_institucional', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Institucional')),
                ('estado', models.CharField(choices=[('DESACTIVADO', 'Desactivado'), ('ACTIVO', 'Activo'), ('RETIRADO', 'Retirado'), ('ABANDONO', 'Abandono')], db_index=True, default='DESACTIVADO', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiantes',
                'ordering': ['apellidos', 'nombres'],
                'indexes': [models.Index(fields=['codigo'], name='idx_estudiante_codigo'), models.Index(fields=['estado'], name='idx_estudiante_estado')],
            },
        ),
        migrations.CreateModel(
            name='MatriculaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_codigo', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Código del Estudiante')),
                ('curso_codigo', models.CharField(db_index=True, max_length=20, verbose_name='Código del Curso')),
                ('ciclo', models.CharField(db_index=True, max_length=10, verbose_name='Ciclo Académico')),
                ('grupo', models.CharField(choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D')], max_length=1, verbose_name='Grupo')),
                ('orden', models.PositiveIntegerField(verbose_name='Orden Alfabético')),
                ('estado', models.CharField(choices=[('MATRICULADO', 'Matriculado'), ('RETIRADO', 'Retirado')], db_index=True, default='MATRICULADO', max_length=20, verbose_name='Estado')),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'matriculas',
                'ordering': ['curso_codigo', 'grupo', 'orden'],
                'indexes': [models.Index(fields=['estudiante_codigo'], name='idx_matricula_estudiante'), models.Index(fields=['curso_codigo', 'ciclo'], name='idx_matricula_curso'), models.Index(fields=['ciclo', 'grupo'], name='idx_matricula_ciclo_grupo')],
                'unique_together': {('estudiante_codigo', 'curso_codigo', 'ciclo')},
            },
        ),
    ]
