# Generated by Django 5.2.7 on 2025-10-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0002_usuariomodel'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuariomodel',
            managers=[
            ],
        ),
    ]
