# Generated by Django 5.2.7 on 2025-10-29 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
