# Generated by Django 5.2.7 on 2025-10-19 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0003_alter_usuariomodel_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratorioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Laboratorio')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('COMPUTO', 'Laboratorio de Cómputo'), ('FISICA', 'Laboratorio de Física'), ('QUIMICA', 'Laboratorio de Química'), ('ELECTRONICA', 'Laboratorio de Electrónica'), ('AULA', 'Aula Regular'), ('AUDITORIO', 'Auditorio')], default='COMPUTO', max_length=20, verbose_name='Tipo de Laboratorio')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad Máxima')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('equipamiento', models.TextField(blank=True, verbose_name='Descripción del Equipamiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Laboratorio Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'db_table': 'laboratorios',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo'], name='idx_laboratorio_codigo'), models.Index(fields=['tipo'], name='idx_laboratorio_tipo'), models.Index(fields=['activo'], name='idx_laboratorio_activo')],
            },
        ),
        migrations.CreateModel(
            name='ReservaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(verbose_name='Fecha de Reserva')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('proposito', models.CharField(max_length=200, verbose_name='Propósito de la Reserva')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada Automáticamente'), ('APROBADA_MANUAL', 'Aprobada Manualmente'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('aprobada_automaticamente', models.BooleanField(default=False, verbose_name='Aprobada Automáticamente')),
                ('motivo_rechazo', models.TextField(blank=True, verbose_name='Motivo de Rechazo')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_docente', to=settings.AUTH_USER_MODEL, verbose_name='Docente Solicitante')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='postgres_repository.laboratoriomodel', verbose_name='Laboratorio')),
                ('procesada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_procesadas', to=settings.AUTH_USER_MODEL, verbose_name='Procesada Por')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['laboratorio', 'fecha_reserva'], name='idx_reserva_lab_fecha'), models.Index(fields=['estado'], name='idx_reserva_estado'), models.Index(fields=['docente'], name='idx_reserva_docente'), models.Index(fields=['fecha_reserva', 'hora_inicio'], name='idx_reserva_horario')],
                'unique_together': {('laboratorio', 'fecha_reserva', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
