# Generated by Django 5.2.7 on 2025-10-30 04:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0005_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('room_type', models.CharField(choices=[('classroom', 'Aula'), ('laboratory', 'Laboratorio'), ('auditorium', 'Auditorio'), ('workshop', 'Taller')], max_length=20, verbose_name='Tipo')),
                ('capacity', models.IntegerField(verbose_name='Capacidad')),
                ('equipment', models.TextField(blank=True, verbose_name='Equipamiento')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aula/Laboratorio',
                'verbose_name_plural': 'Aulas/Laboratorios',
                'db_table': 'classrooms',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='academic_year',
            field=models.CharField(default='2024', max_length=10, verbose_name='Año Académico'),
        ),
        migrations.AddField(
            model_name='course',
            name='cycle',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ciclo'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Duración'),
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.CharField(blank=True, max_length=10, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default='I', max_length=10, verbose_name='Semestre'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='postgres_repository.teacher', verbose_name='Profesor'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_weeks',
            field=models.IntegerField(default=17, verbose_name='Total Semanas'),
        ),
        migrations.AddField(
            model_name='course',
            name='weekly_hours',
            field=models.IntegerField(default=4, verbose_name='Horas Semanales'),
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=200, verbose_name='Nombre de Unidad')),
                ('chapter_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Capítulo')),
                ('topic_number', models.CharField(max_length=20, verbose_name='Número de Tema')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('content_type', models.CharField(choices=[('unit', 'Unidad'), ('chapter', 'Capítulo'), ('topic', 'Tema'), ('subtopic', 'Subtema'), ('exam', 'Examen'), ('assignment', 'Tarea')], default='topic', max_length=20, verbose_name='Tipo')),
                ('week_number', models.IntegerField(verbose_name='Semana')),
                ('order', models.IntegerField(default=1, verbose_name='Orden')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='course_content/', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='postgres_repository.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Contenido del Curso',
                'verbose_name_plural': 'Contenidos del Curso',
                'db_table': 'course_contents',
                'ordering': ['week_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora Fin')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('purpose', models.TextField(verbose_name='Propósito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='postgres_repository.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='postgres_repository.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='postgres_repository.teacher')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(verbose_name='Hora de Ingreso')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('access_type', models.CharField(choices=[('presential', 'Presencial'), ('remote', 'Remoto'), ('virtual', 'Virtual/VPN'), ('unknown', 'Desconocido')], max_length=20, verbose_name='Tipo de Acceso')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='postgres_repository.teacher')),
            ],
            options={
                'verbose_name': 'Asistencia Docente',
                'verbose_name_plural': 'Asistencias Docentes',
                'db_table': 'teacher_attendance',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('late', 'Tardanza'), ('justified', 'Justificado'), ('pending', 'Pendiente')], default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='postgres_repository.course')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgres_repository.teacher', verbose_name='Registrado por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='postgres_repository.student')),
            ],
            options={
                'verbose_name': 'Asistencia Estudiante',
                'verbose_name_plural': 'Asistencias Estudiantes',
                'db_table': 'student_attendance',
                'unique_together': {('student', 'course', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ExamStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_type', models.CharField(choices=[('parcial_1', 'Primer Parcial'), ('parcial_2', 'Segundo Parcial'), ('parcial_3', 'Tercer Parcial'), ('sustitutorio', 'Examen Sustitutorio'), ('final', 'Examen Final'), ('tarea', 'Tarea'), ('proyecto', 'Proyecto')], max_length=20, verbose_name='Tipo de Examen')),
                ('max_grade', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota Máxima')),
                ('min_grade', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota Mínima')),
                ('avg_grade', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota Promedio')),
                ('total_students', models.IntegerField(verbose_name='Total Estudiantes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_stats', to='postgres_repository.course')),
            ],
            options={
                'verbose_name': 'Estadística de Examen',
                'verbose_name_plural': 'Estadísticas de Exámenes',
                'db_table': 'exam_statistics',
                'unique_together': {('course', 'exam_type')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_type', models.CharField(choices=[('parcial_1', 'Primer Parcial'), ('parcial_2', 'Segundo Parcial'), ('parcial_3', 'Tercer Parcial'), ('sustitutorio', 'Examen Sustitutorio'), ('final', 'Examen Final'), ('tarea', 'Tarea'), ('proyecto', 'Proyecto')], max_length=20, verbose_name='Tipo de Evaluación')),
                ('grade_component', models.CharField(max_length=50, verbose_name='Componente')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='postgres_repository.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='postgres_repository.student')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'grades',
                'unique_together': {('student', 'course', 'exam_type', 'grade_component')},
            },
        ),
    ]
