# Generated by Django 5.2.7 on 2025-10-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0006_classroom_course_academic_year_course_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='course',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='group',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_weeks',
        ),
        migrations.RemoveField(
            model_name='course',
            name='weekly_hours',
        ),
    ]
