# Generated by Django 5.2.7 on 2025-11-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0007_remove_course_academic_year_remove_course_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='classes_attended_by_teacher',
            field=models.IntegerField(default=0, verbose_name='Clases asistidas por docente'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='course_progress_percentage',
            field=models.FloatField(default=0.0, verbose_name='Porcentaje de progreso del curso'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='total_planned_classes',
            field=models.IntegerField(default=68, verbose_name='Total de clases programadas'),
        ),
    ]