# Generated by Django 5.2.7 on 2025-11-05 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0002_enhance_teacher_attendance'),
        ('postgres_repository', '0008_add_progress_fields_to_coursegroup'),
    ]

    operations = [
    ]
