# Generated by Django 5.2.7 on 2025-11-05 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0003_add_phase_grades_simple_attendance'),
        ('postgres_repository', '0009_merge_20251104_2042'),
    ]

    operations = [
    ]
