# Generated by Django 5.2.7 on 2025-11-06 02:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0010_merge_20251105_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('late', 'Tardanza'), ('excused', 'Justificado')], max_length=20, verbose_name='Estado')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'db_table': 'attendance_records',
            },
        ),
        migrations.CreateModel(
            name='AttendanceStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_classes', models.IntegerField(default=0, verbose_name='Total de clases')),
                ('present_count', models.IntegerField(default=0, verbose_name='Asistencias')),
                ('absent_count', models.IntegerField(default=0, verbose_name='Faltas')),
                ('late_count', models.IntegerField(default=0, verbose_name='Tardanzas')),
                ('excused_count', models.IntegerField(default=0, verbose_name='Justificadas')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Estadística de Asistencia',
                'verbose_name_plural': 'Estadísticas de Asistencia',
                'db_table': 'attendance_statistics',
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Asignación de Curso',
                'verbose_name_plural': 'Asignaciones de Curso',
                'db_table': 'course_assignments',
            },
        ),
        migrations.CreateModel(
            name='CourseTopicContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_title', models.CharField(max_length=200, verbose_name='Título del Tema')),
                ('topic_description', models.TextField(blank=True, verbose_name='Descripción del Tema')),
                ('topic_order', models.IntegerField(verbose_name='Orden del Tema')),
                ('percentage_weight', models.FloatField(verbose_name='Peso Porcentual')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Contenido del Curso',
                'verbose_name_plural': 'Contenidos del Curso',
                'db_table': 'course_topic_contents',
                'ordering': ['course_group', 'topic_order'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Peso')),
                ('max_score', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Puntaje máximo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Evaluación',
                'verbose_name_plural': 'Tipos de Evaluación',
                'db_table': 'evaluation_types',
            },
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntaje')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Nota',
                'verbose_name_plural': 'Registros de Notas',
                'db_table': 'grade_records_new',
            },
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='course',
        ),
        migrations.RemoveConstraint(
            model_name='phasegrade',
            name='unique_student_course_phase',
        ),
        migrations.RemoveConstraint(
            model_name='simpleattendancerecord',
            name='unique_student_course_date',
        ),
        migrations.AlterUniqueTogether(
            name='phasegrade',
            unique_together={('student', 'course_group', 'phase')},
        ),
        migrations.AlterUniqueTogether(
            name='simpleattendancerecord',
            unique_together={('student', 'course_group', 'class_date')},
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='postgres_repository.coursegroup'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records_new', to='postgres_repository.student'),
        ),
        migrations.AddField(
            model_name='attendancestatistics',
            name='course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_stats', to='postgres_repository.coursegroup'),
        ),
        migrations.AddField(
            model_name='attendancestatistics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_stats', to='postgres_repository.student'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='academic_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='postgres_repository.academicperiod'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='postgres_repository.coursegroup'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='postgres_repository.teacher'),
        ),
        migrations.AddField(
            model_name='coursetopiccontent',
            name='course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_contents', to='postgres_repository.coursegroup', verbose_name='Grupo de Curso'),
        ),
        migrations.AddField(
            model_name='evaluationtype',
            name='course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_types_new', to='postgres_repository.coursegroup'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='evaluation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='postgres_repository.evaluationtype'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='postgres_repository.student'),
        ),
        migrations.DeleteModel(
            name='CourseContent',
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date'], name='idx_attendance_date'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='idx_attendance_status'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['course_group', 'date'], name='idx_attendance_course_date'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'course_group', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendancestatistics',
            index=models.Index(fields=['percentage'], name='idx_attendance_percentage'),
        ),
        migrations.AddIndex(
            model_name='attendancestatistics',
            index=models.Index(fields=['course_group'], name='idx_attendance_course_group'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancestatistics',
            unique_together={('student', 'course_group')},
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('teacher', 'course_group', 'academic_period')},
        ),
        migrations.AddIndex(
            model_name='coursetopiccontent',
            index=models.Index(fields=['course_group'], name='idx_ctc_group'),
        ),
        migrations.AddIndex(
            model_name='coursetopiccontent',
            index=models.Index(fields=['topic_order'], name='idx_ctc_order'),
        ),
        migrations.AddIndex(
            model_name='coursetopiccontent',
            index=models.Index(fields=['is_completed'], name='idx_ctc_completed'),
        ),
        migrations.AlterUniqueTogether(
            name='coursetopiccontent',
            unique_together={('course_group', 'topic_order')},
        ),
        migrations.AddIndex(
            model_name='graderecord',
            index=models.Index(fields=['score'], name='idx_grade_score_new'),
        ),
        migrations.AddIndex(
            model_name='graderecord',
            index=models.Index(fields=['evaluation_type'], name='idx_grade_evaluation_type_new'),
        ),
        migrations.AlterUniqueTogether(
            name='graderecord',
            unique_together={('student', 'evaluation_type')},
        ),
    ]
