# Generated by Django 5.2.7 on 2025-11-10 00:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0011_attendancerecord_attendancestatistics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicperiod',
            name='enrollment_change_deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='academicperiod',
            name='laboratory_enrollment_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='academicperiod',
            name='laboratory_enrollment_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
