# Generated by Django 5.2.8 on 2025-11-17 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0012_alter_academicperiod_enrollment_change_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_set', to='postgres_repository.laboratory', verbose_name='Laboratorio'),
        ),
    ]
