# Generated by Django 5.2.8 on 2025-11-22 04:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0013_horario_laboratory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_weeks', models.IntegerField(default=16, verbose_name='Total de Semanas')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='postgres_repository.academicperiod', verbose_name='Período Académico')),
                ('course_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='postgres_repository.coursegroup', verbose_name='Grupo de Curso')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postgres_repository.teacher', verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Sílabo',
                'verbose_name_plural': 'Sílabos',
                'db_table': 'syllabi',
                'unique_together': {('course_group', 'academic_period')},
            },
        ),
        migrations.CreateModel(
            name='SyllabusMainTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(verbose_name='Orden')),
                ('title', models.CharField(max_length=300, verbose_name='Título del Tema')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_topics', to='postgres_repository.syllabus', verbose_name='Sílabo')),
            ],
            options={
                'verbose_name': 'Tema Principal',
                'verbose_name_plural': 'Temas Principales',
                'db_table': 'syllabus_main_topics',
                'ordering': ['syllabus', 'order'],
                'unique_together': {('syllabus', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SyllabusSubTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(verbose_name='Orden')),
                ('title', models.CharField(max_length=300, verbose_name='Título del Subtema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='postgres_repository.syllabusmaintopic', verbose_name='Tema Principal')),
            ],
            options={
                'verbose_name': 'Subtema',
                'verbose_name_plural': 'Subtemas',
                'db_table': 'syllabus_subtopics',
                'ordering': ['main_topic', 'order'],
                'unique_together': {('main_topic', 'order')},
            },
        ),
    ]
