# Generated by Django 5.2.8 on 2025-11-27 00:39

import django.core.validators
import django.db.models.deletion
import repositorio.postgres_repository.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0014_syllabus_syllabusmaintopic_syllabussubtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAccreditation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('primera', 'Primera Fase'), ('segunda', 'Segunda Fase'), ('tercera', 'Tercera Fase')], max_length=20, verbose_name='Fase Académica')),
                ('exam_number', models.IntegerField(choices=[(1, 'Primer Parcial'), (2, 'Segundo Parcial'), (3, 'Tercer Parcial')], verbose_name='Número de Parcial')),
                ('exam_file', models.FileField(help_text='Solo se permiten archivos PDF o PNG', upload_to=repositorio.postgres_repository.models.exam_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png'])], verbose_name='Archivo del Examen')),
                ('max_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Máxima')),
                ('min_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Mínima')),
                ('average_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Promedio')),
                ('total_students', models.IntegerField(default=0, verbose_name='Total de Estudiantes')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Tamaño del Archivo (bytes)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción/Observaciones')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_accreditations', to='postgres_repository.coursegroup', verbose_name='Grupo de Curso')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_exams', to='postgres_repository.teacher', verbose_name='Profesor que Subió')),
            ],
            options={
                'verbose_name': 'Acreditación de Examen',
                'verbose_name_plural': 'Acreditaciones de Exámenes',
                'db_table': 'exam_accreditations',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['course_group', 'phase'], name='idx_exam_accred_course_phase'), models.Index(fields=['uploaded_by'], name='idx_exam_accred_teacher'), models.Index(fields=['uploaded_at'], name='idx_exam_accred_date'), models.Index(fields=['phase', 'exam_number'], name='idx_exam_accred_phase_num')],
                'unique_together': {('course_group', 'phase', 'exam_number')},
            },
        ),
    ]
