# Generated by Django 5.2.8 on 2025-11-27 02:33

import django.core.validators
import django.db.models.deletion
import repositorio.postgres_repository.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0015_examaccreditation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examaccreditation',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='examaccreditation',
            name='idx_exam_accred_course_phase',
        ),
        migrations.RemoveIndex(
            model_name='examaccreditation',
            name='idx_exam_accred_teacher',
        ),
        migrations.RemoveIndex(
            model_name='examaccreditation',
            name='idx_exam_accred_date',
        ),
        migrations.RemoveIndex(
            model_name='examaccreditation',
            name='idx_exam_accred_phase_num',
        ),
        migrations.AlterUniqueTogether(
            name='examaccreditation',
            unique_together={('course_group', 'exam_number')},
        ),
        migrations.AddField(
            model_name='examaccreditation',
            name='best_exam_file',
            field=models.FileField(blank=True, null=True, upload_to=repositorio.postgres_repository.models.exam_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png'])], verbose_name='Examen Mejor Nota'),
        ),
        migrations.AddField(
            model_name='examaccreditation',
            name='worst_exam_file',
            field=models.FileField(blank=True, null=True, upload_to=repositorio.postgres_repository.models.exam_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png'])], verbose_name='Examen Peor Nota'),
        ),
        migrations.AlterField(
            model_name='examaccreditation',
            name='average_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='examaccreditation',
            name='course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_accreditations', to='postgres_repository.coursegroup'),
        ),
        migrations.AlterField(
            model_name='examaccreditation',
            name='exam_number',
            field=models.IntegerField(choices=[(1, 'Primer Parcial'), (2, 'Segundo Parcial'), (3, 'Tercer Parcial')]),
        ),
        migrations.AlterField(
            model_name='examaccreditation',
            name='max_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='examaccreditation',
            name='min_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='examaccreditation',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examaccreditation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='examaccreditation',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examaccreditation',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_exams', to='postgres_repository.teacher'),
        ),
        migrations.AlterModelTable(
            name='examaccreditation',
            table=None,
        ),
        migrations.RemoveField(
            model_name='examaccreditation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='examaccreditation',
            name='exam_file',
        ),
        migrations.RemoveField(
            model_name='examaccreditation',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='examaccreditation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='examaccreditation',
            name='phase',
        ),
    ]
