# Generated by Django 5.2.9 on 2025-12-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0016_alter_examaccreditation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroup',
            name='enrolled_students',
        ),
    ]
