# Generated by Django 5.2.9 on 2025-12-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0017_remove_coursegroup_enrolled_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
