# Generated by Django 5.2.9 on 2025-12-17 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0018_alter_laboratory_capacity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('course_group', 'laboratory', 'aula', 'dia_semana', 'hora_inicio')},
        ),
    ]
