# Generated by Django 5.2.8 on 2026-01-07 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_repository', '0019_alter_horario_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='postgres_repository.teacher'),
        ),
    ]
